# Generated by Django 2.1.11 on 2019-09-02 13:05

from django.db import migrations

from users.signals import generate_and_save_allowed_origins_from_client_configurations


def populate_allowed_origin(apps, schema_editor):
    generate_and_save_allowed_origins_from_client_configurations(None, None)


def _noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_add_oauth2_application_fields'),
    ]

    operations = [
        migrations.RunPython(populate_allowed_origin, _noop),
    ]
