# Generated by Django 2.2.7 on 2020-11-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_merge_20191031_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmethod',
            name='disabled',
            field=models.BooleanField(
                default=False, verbose_name='disable login method',
                help_text='Set if this login method should be unselectable'
            )
        )
    ]
