language: python
python:
  - '3.12'

sudo: false

cache: pip

before_install:
  - pip install -U pip

install: 'pip install codecov -r requirements.txt -r requirements-dev.txt'

script:
  - flake8
  - isort -c
  - pytest -ra -vvv --cov=.
  - pip install pip-tools
  - pip-compile --quiet --check requirements.in

addons:
  postgresql: '15'
  apt:
    packages:
    - libxmlsec1-dev
    - pkg-config

after_success: codecov
